version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  app:
    image: scootin-aboot-1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - redis
